version: '3.4'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: deandraper
      POSTGRES_PASSWORD: spacework1821
    ports:
      - '5432:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  workspacedescriptionservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6060:6060
